title: Practice Page
author: Jester F
email: jester@fools.work
description: > # this means to ignore newlines until "baseurl:"
  Practice page for the page I wanna make
# social links
twitter_username: jesterf # DO NOT include the @ character, or else the build will fail!
github_username:  jesterf # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
